version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.3.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      # run tests!
      - run: npx eslint src
      - run: npm test -- --reporters=default --reporters=jest-junit
      - store_test_results: junit.xml
      - run: npx babel -d dist src
      - run: cd react-demo && npx rollup -c
