version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-1

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-1

      # run tests!
      - run: npm run lint
      - run:
          name: jest src
          command: mkdir -p test-results/jest && npm test -- --reporters=default --reporters=jest-junit
      - store_test_results:
          path: test-results
      - run: npx babel -d dist src
      - run: cd react-demo && npm ci && npx rollup -c
